layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  scope:
    path: "" # an empty string here means all files in the project
    type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  limit:
  exclude:
    archived: true
    forks: false
    projects:
      - web-m
  include:
    - csc480-19s/SMARTron
    - untitled01exe/IntCoin
    - kgordo/CSC445P2
    - untitled01exe/GoMuxer
    #- untitled01exe/goassign/blob/master/g.go
    #- untitled01exe/380_library_game

social_media:
  website: http://jackalope.design
  instagram: fantastic.fernando

#topics:
#  - name: Android
#    web_url: https://github.com/topics/android
#    image_url: https://raw.githubusercontent.com/github/explore/a3520d60fbf9b0bdd0b7d563a1a3ed596acd8489/topics/android/android.png

#  - name: Kotlin
#    web_url: https://github.com/topics/kotlin
#    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/kotlin/kotlin.png

#  - name: Gradle
#    web_url: https://github.com/topics/gradle
#    image_url: https://raw.githubusercontent.com/github/explore/e63ac6ef59c5c316574b0d31942f0534e51265a8/topics/gradle/gradle.png

#  - name: Firebase
#    web_url: https://github.com/topics/firebase
#    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/firebase/firebase.png
